LEXICON = {
    'start_message_no_sessions': "<b>Welcome to the Monitoring Bot!</b>\n\nYou don't have any connected accounts yet. Let's add your first one to get started.",
    'session_menu_title': "<b>🎛️ Session Management</b>\n\nSelect an account to manage or add a new one.",
    'session_details_template': "<b>Account Details</b>\n\n👤 <b>Name:</b> {first_name} {last_name}\n📞 <b>Phone:</b> <code>{phone}</code>\n🆔 <b>User ID:</b> <code>{user_id}</code>\n\n<b>Connection:</b> {status}\n<b>Monitoring:</b> {monitoring_status}",
    'my_chats_button': " monitored chats",
    'chat_list_title': "<b> monitored chats</b>\n\nHere is the list of chats and users you are monitoring with this account.",
    'chat_details_title': "<b>Managing Chat:</b> {chat_title}",
    'chat_deleted_success': "✅ <b>{chat_title}</b> has been removed from the monitoring list.",
    'add_chat_success': "✅ Successfully joined <b>{chat_title}</b> and added it to the monitoring list.",
    'success_connection': "✅ <b>Success!</b>\n\nYour account has been connected.",
    'error_generic': "An unexpected error occurred. Please try again later.",
    'add_new_account_button': "➕ Add New Account",
    'delete_button': "🗑️ Delete",
    'add_chat_button': "📡 Add Entity to Monitor",
    'start_monitoring_button': "▶️ Start Monitoring",
    'stop_monitoring_button': "⏹️ Stop Monitoring",
    'back_button': "⬅️ Back to Sessions",
    'back_to_chats_button': "⬅️ Back to Chat List",
    'cancel_button': "❌ Cancel",
    'chat_settings_button': "⚙️ Settings",
    'chat_settings_title': "<b>⚙️ Settings for:</b> {chat_title}",
    'chat_settings_menu_text': ("<b>Frequency:</b> {frequency}s\n" "<b>Initial Fetch:</b> {initial_fetch} msgs\n" "<b>DB Auto-Clean:</b> {autoclean_limit}\n" "<b>Download Media:</b> {download_media}\n" "<b>Detect Deletions:</b> {detect_deletions}"),
    'autoclean_disabled_text': "Disabled",
    'autoclean_enabled_text': "{count} msgs",
    'on_text': "ON",
    'off_text': "OFF",
    'set_frequency_button': "Set Frequency",
    'set_initial_fetch_button': "Set Initial Fetch",
    'set_autoclean_button': "Set DB Auto-Clean",
    'toggle_media_button': "Toggle Media Download",
    'toggle_deletions_button': "Toggle Deletion Detection",
    'back_to_chat_details_button': "⬅️ Back to Chat Details",
    'prompt_frequency': "Please send the new check frequency in seconds (e.g., 10). Minimum is 5.",
    'prompt_initial_fetch': "Please send the number of messages to fetch when a chat is first added (e.g., 20).",
    'prompt_autoclean': "Please send the maximum number of messages to keep in the database for this chat. Send 0 to disable auto-cleaning.",
    'error_invalid_number': "⚠️ Please send a valid positive number.",
    'setting_updated_alert': "✅ Setting updated!",
    'deletion_notification_title': "<b>🗑️ Message Deleted</b>",
    'deletion_notification_body': ("In chat: <b>{chat_title}</b>\nMonitored by: <code>{session_phone}</code>\nDate sent: {date}\n\n"),
    'deleted_text_content': "<b>Content:</b>\n<pre>{text}</pre>",
    'deleted_file_content': "<b>Attached File:</b> <code>{file_path}</code>",
    'deleted_media_only_content': "<i>(Message contained media but no text)</i>",
    'confirm_delete_prompt': "⚠️ <b>Are you sure?</b>\n\nDo you really want to delete the session for <b><code>{phone}</code></b>? This action cannot be undone.",
    'session_deleted_message': "✅ Session for <b><code>{phone}</code></b> has been successfully deleted.",
    'session_set_active_alert': "✅ Session for {phone} is now active.",
    'monitoring_status_active': "🟢 Active",
    'monitoring_status_inactive': "⚪ Inactive",
    'monitoring_started_alert': "▶️ Monitoring has been started for this session.",
    'monitoring_stopped_alert': "⏹️ Monitoring has been stopped for this session.",
    'no_chats_monitored': "You are not monitoring any chats or users with this account yet. Add one to get started!",
    'confirm_delete_chat_prompt': "⚠️ <b>Are you sure?</b>\n\nDo you really want to remove <b>{chat_title}</b> from the monitoring list? The account will remain in the chat, but the bot will stop tracking it.",
    'add_user_success': "✅ Successfully added user <b>{user_name}</b> to the monitoring list.",
    'add_chat_already_joined': "✅ This account is already a member of <b>{chat_title}</b>. Added to the monitoring list.",
    'prompt_api_id': "<b>Step 1: API ID</b>\n\nPlease send your <code>api_id</code>.",
    'prompt_api_hash': "<b>Step 2: API Hash</b>\n\nGreat! Now please send your <code>api_hash</code>.",
    'prompt_phone': "<b>Step 3: Phone Number</b>\n\nFinally, enter the phone number in international format.",
    'prompt_code_interactive': "A confirmation code has been sent. Please enter it below.\n\nEntered code: {masked_code}",
    'prompt_password': "<b>Two-Factor Authentication</b>\n\nYour account is protected by a password. Please send it.",
    'code_resent': "A new confirmation code has been sent.",
    'invalid_code_alert': "⚠️ Invalid Code. Please try again.",
    'error_api_id': "⚠️ Invalid input. The <code>api_id</code> must be a number.",
    'error_phone': "⚠️ Invalid format. e.g., <code>+12345678900</code>.",
    'error_invalid_password': "⚠️ The password you entered is incorrect. Please try again.",
    'add_chat_not_found': "⚠️ Could not find the specified chat, channel, or user. Please check the identifier and try again.",
    'prompt_add_chat': "Please send the username, join link, or ID of the channel, chat, or user you want to monitor.",
    'add_chat_error': "An unexpected error occurred while trying to add the entity.",
    'cancellation_message': "Action cancelled. You have been returned to the main menu.",
    'set_active_button': "✅ Set Active",
    'delete_chat_button': "🗑️ Remove from Monitoring",
    'confirm_delete_yes': "Yes, Delete",
    'confirm_delete_no': "No, Cancel",
    'resend_code_button': "🔄 Resend Code",
    'first_page': "« First",
    'prev_page': "‹ Prev",
    'next_page': "Next ›",
    'last_page': "Last »",
    'page_counter': "Page {current_page}/{total_pages}",
    'delete_button_kb': "⌫",
    'send_code_button': "➤ Send Code",
    'statistics_button': "📊 Statistics",
    'statistics_title': "<b>📊 Chat Statistics for {phone}</b>\n\nSelect a chat to view detailed stats. Use the buttons below to sort the list.",
    'no_stats_yet': "No messages have been logged for any chat yet. Statistics will appear here once monitoring begins.",
    'detailed_stats_title': "<b>📊 Statistics for:</b> {chat_title}",
    'detailed_stats_template': (
        "<b>Overall Activity</b>\n"
        "  - Total Messages Logged: <code>{total_messages}</code>\n"
        "  - First Message: <code>{first_message}</code>\n"
        "  - Last Message: <code>{last_message}</code>\n\n"
        "<b>Deletions</b>\n"
        "  - Detected Deletions: <code>{deleted_messages}</code>\n"
        "  - Deletion Rate: <code>{deletion_rate:.2f}%</code>\n\n"
        "<b>Media & Volume</b>\n"
        "  - Media Files Downloaded: <code>{media_files}</code>\n"
        "  - Total Volume: <code>{media_volume}</code>"
    ),
    'stats_not_available': "N/A",
    'back_to_stats_button': "⬅️ Back to Statistics",
    'sort_by_total': "Sort: Total Msgs",
    'sort_by_deleted': "Sort: Deletions",
    'sort_by_volume': "Sort: Volume",
    'sort_by_activity': "Sort: Activity",
}